name: efficient_indexed_stack
description: It's an IndexedStack that only builds the widgets that are in the range of the
  current index and the keepAliveDistance
version: 1.0.1
homepage: https://github.com/EnesKaraosman/efficient_indexed_stack

environment:
  sdk: '<4.0.0'
  flutter: ">=3.3.10"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# The following section is specific to Flutter packages.
flutter:
